build:
  environment:
    python: 3.7.1

filter:
  dependency_paths:
    - "omaha_server/assets/components/bower_components/"
  excluded_paths:
    - "*/migrations/*"
dependencies:
  before:
    - pip install pysqlite3