build:
  environment:
    python: 3.6.9
  tests:
   override:
     command: "python --version"

filter:
  dependency_paths:
    - "omaha_server/assets/components/bower_components/"
  excluded_paths:
    - "*/migrations/*"