build:
  environment:
    python: 3.7.1
  nodes:
    tests:
      dependencies:
        before:
          - apt-get update sqlite3

filter:
  dependency_paths:
    - "omaha_server/assets/components/bower_components/"
  excluded_paths:
    - "*/migrations/*"
