language: python
dist: xenial
python:
  - "3.6"

addons:
  apt:
    packages:
    - python-lxml
    - python-psycopg2
    - python-dev

env:
  global:
    - HOST_NAME: 'travis-ci'
    - SECRET_KEY: 'SECRET_KEY'
    - GRPC_PYTHON_BUILD_WITH_CYTHON: 1

cache: pip
sudo: false

services:
  - redis-server
  - postgresql

install:
  - pip install tox==3.9.0
  - pip install google-compute-engine

stages:
  - name: test

jobs:
  include:
    - stage: test
      script:
        - tox -e py36
      env:
        - OMAHA_SERVER_PRIVATE=True
    - stage: test
      script:
        - tox -e py36
      env:
        - OMAHA_SERVER_PRIVATE=False
    - stage: test
      script:
        - tox -e py36
        - if [ $COVERAGE = true ] ; then coveralls --skip_ssl_verify; fi
      env:
        - OMAHA_SERVER_PRIVATE=True
        - DJANGO_SETTINGS_MODULE=omaha_server.settings_test_postgres
    - stage: test
      script:
        - tox -e py36
      env:
        - OMAHA_SERVER_PRIVATE=False
        - DJANGO_SETTINGS_MODULE=omaha_server.settings_test_postgres
        - PATH_TO_TEST=omaha.tests.test_public

