language: python
dist: xenial
matrix:
  allow_failures:
    - env: TOX_ENV=py34
  include:
    - python: "2.7"
      env:
        - OMAHA_SERVER_PRIVATE=True
        - PATH_TO_TEST=''
        - DJANGO_SETTINGS_MODULE=omaha_server.settings_test
    - python: "2.7"
      env:
        - OMAHA_SERVER_PRIVATE=False
        - PATH_TO_TEST=''
        - DJANGO_SETTINGS_MODULE=omaha_server.settings_test
    - python: "2.7"
      env:
        - PATH_TO_TEST=''
        - DJANGO_SETTINGS_MODULE=omaha_server.settings_test_postgres
    - python: "2.7"
      env:
        - PATH_TO_TEST=omaha.tests.test_public
        - DJANGO_SETTINGS_MODULE=omaha_server.settings_test_postgres
        - OMAHA_SERVER_PRIVATE=False
    - python: "2.7"
      env: TOX_ENV=coverage

cache: pip
sudo: false

virtualenv:
  system_site_packages: false

addons:
  apt:
    packages:
     - python-dev

env:
  global:
    - HOST_NAME: 'travis-ci'
    - SECRET_KEY: 'SECRET_KEY'
    - GRPC_PYTHON_BUILD_WITH_CYTHON: 1
    - AWS_ACCESS_KEY_ID: 'fake'
    - AWS_SECRET_ACCESS_KEY: 'fake'

services:
  - redis-server

install:
  - pip install -r omaha_server/requirements_dev.txt

before_script: cd omaha_server
script:
  - ./manage.py test $PATH_TO_TEST
# coveralls --skip_ssl_verify