version: '2'
services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  redis:
    extends:
      file: docker-compose.common.yml
      service: redis
    ports:
      - "6379:6379"

  django:
    extends:
      file: docker-compose.common.yml
      service: django
    links:
      - db
      - redis
    ports:
        - "8080:8000"
    volumes:
        - ./cup_pem_keys:/usr/src/app/cup_pem_keys
volumes:
  postgres-data:
