version: '2'
services:
  db:
    restart: always
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  redis:
    restart: always
    image: redis:5

  django:
    privileged: true
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: ''
      HOST_NAME: '*'
      SECRET_KEY: 'asdfghjklqwertzuiop'
      DJANGO_SETTINGS_MODULE: 'omaha_server.settings_prod'
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: "ca-central-1"
      AWS_REGION: "ca-central-1"
      AWS_STORAGE_BUCKET_NAME: 'ca-central-1-omaha-s3bucket'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OMAHA_SERVER_PRIVATE: 'True'
      AWS_ROLE: ''
      DB_PUBLIC_USER: 'omaha_public'
      DB_PUBLIC_PASSWORD: 'omaha_public_password'
      UWSGI_PROCESSES: 10
      UWSGI_THREADS: 8
      FILEBEAT_HOST: 'localhost'
      FILEBEAT_PORT: '9021'
      ELK_HOST: ''
      ELK_PORT: ''
      FILEBEAT_DESTINATION: ''
      SENTRY_DSN: 'https://d22e416e3a414956a2cf22b15922bc0c@sentry.aws.dwos.com/3'
