version: '2'
services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  redis:
    extends:
      file: docker-compose.common.yml
      service: redis
    ports:
      - "6379:6379"

  django_migration:
    extends:
      file: docker-compose.common.yml
      service: django
    command: bash -c " python manage.py makemigrations && python manage.py migrate && python createadmin.py"
    depends_on:
      - db
      - redis
  django:
    container_name: django
    extends:
      file: docker-compose.common.yml
      service: django
    depends_on:
      django_migration:
        condition: service_completed_successfully
    volumes:
        - ./cup_pem_keys:/usr/src/app/cup_pem_keys
    ports:
        - "8080:8000"
volumes:
  postgres-data:
