# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 12:41
from __future__ import unicode_literals

from django.db import migrations
import omaha.fields


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0034_rename_successsaction_to_onsuccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='version',
            field=omaha.fields.BigVersionField(blank=True, default=0, help_text='Format: 255.255.65535.65535', null=True),
        ),
    ]
